In [1]:
import numpy as np

## Araligi Esit Uzakliktaki Noktalara Bolmek
* Belirlenen [baslangic, bitis]degerlerine gore baslangic ve bitisi dahil edecek sekilde, araligi esit uzakliktaki noktalara bolmek.
* Default olrarak 50 nokta dondurur.
* Baslangic ve son da dahil.

In [2]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

### Kac Parcaya Bolecegini Belirtmek

In [4]:
# 1 ve 2 arasini esit 3 sayiya bolecek. Buna 1 ve 2 de dahil.
np.linspace(1,2, num=3)

array([1. , 1.5, 2. ])

In [6]:
# num diye belirtmeye gerek yok.
np.linspace(1,2,3)

array([1. , 1.5, 2. ])

In [7]:
# endpoint=False oldugu icin 2 yi dahil etmeyecek ve boyle 3 parcaya bolecek.
np.linspace(1,2, num=3, endpoint=False)

array([1.        , 1.33333333, 1.66666667])

* Sadece int degerler icin degil floatlar icin de gecerli.

In [8]:
np.linspace(1.5,4.5,num=3)

array([1.5, 3. , 4.5])

## Normal Distribution'dan Cekilmis Degerler Ile Array Olusturma
* (mean,std,array size)

In [13]:
np.random.normal(0,1,(4,5))

array([[-1.06734505, -0.57223334,  0.73214432, -0.19105053, -0.51620248],
       [ 1.52197088,  0.36927955, -0.47842264, -0.40751953,  0.47987967],
       [ 0.17985399, -0.89617811,  0.69795122,  0.31958266, -1.30750593],
       [-1.84815897,  1.29363183,  0.19668627, -1.35016934,  0.43274683]])

In [15]:
np.random.normal(10,5,(4,5))

array([[ 0.80356957, 15.1901022 , 11.9739075 , 16.5739359 ,  7.64947665],
       [11.84038846,  6.89482819,  7.09917645,  7.17529479,  5.73595171],
       [11.25735039, 14.21395093,  9.64922726,  3.72396395, 16.50511386],
       [18.50463871, 15.54737524, -1.63444787,  8.05794129, 16.80457494]])

## Random Integer'lar Ile Array Olusturmak
* [low,high)

In [16]:
np.random.randint(1,10,(3,4))

array([[4, 2, 7, 5],
       [1, 2, 5, 3],
       [6, 3, 3, 2]])

In [18]:
np.random.randint(1,10)

5

## Identity(Birim) Matrix Olusturmak
* [low,high)

In [19]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [20]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])