In [1]:
import numpy as np

## Elemanlari 0'lardan Olusan Array Olusturmak

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

* Str de 0 yerine konulan sey bosluk yani " " oldugu icin 0 yerine onu koyuyor  

In [3]:
np.zeros(10, dtype = str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [4]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Elemanlari 0'lardan Olusan Multidimensional Array Olusturmak
* Cok boyutlu arraylar olusturabiliyoruz.

In [6]:
# 5 Satir(Row) ve 4 Sutun(Column)'u olan bir array olusturduk.
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# 2 Tane 3 Row ve 4 Column dan olusan bir array olusturduk.
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [9]:
np.zeros((2,2), dtype = str)

array([['', ''],
       ['', '']], dtype='<U1')

* Bool veri tipinde 0 olarak aldigi sey False. Bu sebeple 0 yerine False koyuyor.

In [11]:
np.zeros((2,2), dtype = bool)

array([[False, False],
       [False, False]])

## Belirtilen Bir Elemandan Array Olusturma

In [12]:
np.full((4,5), 5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

* Diyelimki bizim 4.3 gibi bir float sayimiz var. Bunu normalde str e cevirirsek "4.3" olur ama arraylarde bunu str yapmaya kalktigimizda bu basta int a donusum sonrasinda str e donustugu icin "4" oluyor.

In [14]:
str(4.3)

'4.3'

In [13]:
np.full((2,4),4.3, dtype = "str")

array([['4', '4', '4', '4'],
       ['4', '4', '4', '4']], dtype='<U1')

* Ama 4.3 yi direkt "4.3" olarak verirsek her hangi bir donusum islemi olmadigi icin degisim olmuyor.

In [15]:
np.full((2,4), "4.3")

array([['4.3', '4.3', '4.3', '4.3'],
       ['4.3', '4.3', '4.3', '4.3']], dtype='<U3')

## Ardisik Sayilardan Array Olusturmak

* range() foksiyonunun numpy arrayi olusturan hali.

In [17]:
#[2,11)
np.arange(2,11)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

* Asagida iki sonucun farkli olmasinin sebebi baslangic dahil iken sonun dahil olmayisi cunku foksiyon [13,4) oldugunda 4 buna dahil olmuyor.

In [21]:
np.arange(13,4,-3)

array([13, 10,  7])

In [22]:
np.arange(13,1,-3)

array([13, 10,  7,  4])