In [65]:
import numpy as np

## Multidimensional Arraylarin Elemanlarina Ulasmak

In [66]:
a = np.arange(1,21).reshape(4,5)

In [67]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [68]:
a[0]

array([1, 2, 3, 4, 5])

In [69]:
a[1]

array([ 6,  7,  8,  9, 10])

In [70]:
a[0,0]

1

In [71]:
a[1,1]

7

In [72]:
a[1,1] = 10

In [73]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 10,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Slice Indexing

In [74]:
a = np.arange(1,21).reshape(4,5)

In [75]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [76]:
a[0:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [77]:
a[:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [78]:
a[0:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [79]:
a[1:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

* [Start:Stop:Step]

In [80]:
a[::2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [81]:
a


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [82]:
a[2,3]

14

* Butun rowlari al ama sadece 3.indexteki column u al.

In [83]:
a[:,3]

array([ 4,  9, 14, 19])

In [84]:
a[0,2:4]

array([3, 4])

In [85]:
a[:2,:3]

array([[1, 2, 3],
       [6, 7, 8]])

## Fancy Indexing
* Fancy indexing ile bir kac tane belirli indexteki elemani bana dondur diyebilmis olacagiz.

In [86]:
x = np.arange(1,15)

In [87]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [88]:
idxs = [4,5,7,11]

* 4 5 7 ve 11 indexteki elemanlari dondurdu

In [89]:
x[idxs]

array([ 5,  6,  8, 12])

In [90]:
b = np.arange(12).reshape(3,4)

In [91]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [92]:
a[0:2,1]

array([2, 7])

In [93]:
a[0:2,1].shape

(2,)

In [94]:
a[0,[1,3]]

array([2, 4])

In [95]:
a[0,[1,3]]

array([2, 4])

* Fancy index sonucunu belirli degerlere esitmelemek.

In [96]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [97]:
x[[1,2,3]] = 20

In [98]:
x

array([ 1, 20, 20, 20,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [99]:
x = np.arange(9)

In [100]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [101]:
x[[1,2,5]] = [100,200,300]

In [102]:
x

array([  0, 100, 200,   3,   4, 300,   6,   7,   8])

## Subarray

In [103]:
a = np.arange(1,21).reshape(4,5)

In [104]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [105]:
b = a[:2,:3]

In [106]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [107]:
b.ndim

2

In [108]:
b[0,0] = 100

In [109]:
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [110]:
a

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

### Copy
* copy() metodunu kullanirsak subarray in degerinin degismesi orjinal array i etkilemez.

In [111]:
a = np.arange(1,21).reshape(4,5)

In [112]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [113]:
b = a[:2,:3].copy()

In [114]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [115]:
b[0,0] = 100

In [116]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [117]:
b

array([[100,   2,   3],
       [  6,   7,   8]])