In [2]:
import numpy as np 

## Array İşlemleri

In [3]:
# * operatoru iki list arasinda tanimsizdir, hata verir

a = [1,2,3]
b = [2,4,8]

a * b

TypeError: can't multiply sequence by non-int of type 'list'

* List ile integer carpilirsa ard arda concatenation yapar

In [5]:
[4,2,5] * 3

[4, 2, 5, 4, 2, 5, 4, 2, 5]

In [6]:
[2,4,8] + [2,4,8] + [2,4,8]

[2, 4, 8, 2, 4, 8, 2, 4, 8]

* "*" operetoru iki numpy arayi arasinda tanimlidir, element-wise(eleman bazli) carpma yapar

In [7]:
x = np.array([1,2,3])
y = np.array([2,4,8])

x * y

array([ 2,  8, 24])

* element-wise carpim yaptigi icin carpilan iki array'in eleman sayisi ayni olmali

In [8]:
#Eleman sayisi ayni olmadigi icin hata veriyor.
x2 = np.array([1,2,3])
y2 = np.array([2,4,8,10])

x2 * y2

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [10]:
#Bunlar list oldugu icin direk listeleri birlestiriyor.
a + b

[1, 2, 3, 2, 3, 8]

In [11]:
#Bunlar numpy array oldugu icin bunlar toplaniyor.
x + y

array([ 3,  6, 11])

In [15]:
a

[1, 2, 3]

In [16]:
#Liste oldugu icin listeyi 3 kere carpti ve birlstirdir
3 * a

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [17]:
x

array([1, 2, 3])

In [18]:
#Numpy array oldugu icin icindeki degerler 3 ile carpiliyor.
3 * x

array([3, 6, 9])

* Deger guncellemek icin

In [19]:
x = x * 3

In [20]:
x

array([3, 6, 9])