In [1]:
import numpy as np

## Conditional Indexing

In [2]:
a = np.arange(1,10)

In [3]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a < 5

array([ True,  True,  True,  True, False, False, False, False, False])

In [5]:
a[a<5]

array([1, 2, 3, 4])

In [6]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
filt = a < 3

In [8]:
a[filt]

array([1, 2])

In [9]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
b = np.array([2,3,3,4,5,61,7,8,11])

In [11]:
b

array([ 2,  3,  3,  4,  5, 61,  7,  8, 11])

* Ortak olan elemanlar True digerleri False oluyor.

In [12]:
a == b

array([False, False,  True,  True,  True, False,  True,  True, False])

*  Ortak olan elemanlari gosteriyor.

In [15]:
a[a==b]

array([3, 4, 5, 7, 8])

In [16]:
b[a==b]

array([3, 4, 5, 7, 8])

In [17]:
a == [1]

array([ True, False, False, False, False, False, False, False, False])

In [18]:
a == 1

array([ True, False, False, False, False, False, False, False, False])

* or yerine | koymamiz gerek.

In [19]:
(a < 3) or (a > 5)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [20]:
(a < 3) | (a > 5)

array([ True,  True, False, False, False,  True,  True,  True,  True])

In [21]:
a[(a < 3) | (a > 5)]

array([1, 2, 6, 7, 8, 9])

In [22]:
filt = (a < 3) | (a > 5)

In [23]:
filt

array([ True,  True, False, False, False,  True,  True,  True,  True])

* and yerine de &

In [24]:
a[(a < 3) & (a > 5)]

array([], dtype=int64)

## Filtrenin Degili
* degili icin ~ kullanmamiz gerek.

In [30]:
a = np.arange(1,21).reshape(4,5)

In [31]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [32]:
~((a>5) & (a<9))

array([[ True,  True,  True,  True,  True],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [33]:
filt = ~((a>5) & (a<9))

In [34]:
a[filt]

array([ 1,  2,  3,  4,  5,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

## Multidimensional Array

In [35]:
a = np.arange(1,21).reshape(4,5)

In [36]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [37]:
type(a)

numpy.ndarray

In [38]:
a < 7

array([[ True,  True,  True,  True,  True],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [39]:
a[a<7]

array([1, 2, 3, 4, 5, 6])

In [40]:
a[a<7].shape

(6,)

## Sum

In [43]:
a = np.arange(1,21).reshape(4,5)

In [44]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

* Butun degeleri topluyor.

In [45]:
np.sum(a)

210

* Verilen conditioni kac elemanin sagladigini bulmamizi saglar.

In [50]:
filt = a < 5

In [51]:
filt

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [52]:
np.sum(filt)

4

In [53]:
a[filt]

array([1, 2, 3, 4])

In [54]:
np.sum(~((a>5) & (a<9)))

17

In [55]:
np.sum(a[~((a>5) & (a<9))])

189

### Belirli axis uzrinde toplama

In [56]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [57]:
np.sum(a, axis = 0)

array([34, 38, 42, 46, 50])

In [58]:
np.sum(a, axis = 1)

array([15, 40, 65, 90])

## ALL
* Tum elemanlar verilen sarti sagliyor mu kontrol etmek icin.

In [3]:
a = np.arange(20).reshape(4,5)

In [4]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [5]:
a>-1

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

* Hepsi True oldugu icin True degeri dondurdu.

In [7]:
np.all(1>-1)

True

* Hepsi True olmadigi icin False dondurdu.

In [16]:
a>5

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [17]:
np.all(1>5)

False

* Axis bazli bakti. 4 tane axis in hepsininkine yari ayri bakti.

In [18]:
np.all(a>5, axis = 1)

array([False, False,  True,  True])

* Axis = 0 da ise y ekseni bazli ayri ayri bakti.
* Hepsi False cunku hepsinde en az 1 tane False var.

In [19]:
np.all(a>5, axis = 0)

array([False, False, False, False, False])

## ANY
* All da True dondurmesi icin hepsinin True olmasi gerekirken. Any de biririnin True olmasi True dondurmesi icin yeterli.

In [21]:
a = np.arange(20).reshape(4,5)

In [22]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [23]:
a>17

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True]])

* Sadece birinin kosulu karsilamasi True icin yeterli.

In [26]:
np.any(a>17)

True

* Sadece son satida kosulu karsilayan ifade var. Satir Bazli bakiyor.

In [35]:
np.any(a>17, axis=1)

array([False, False, False,  True])

* Stun bazli bakiyor. Sadece Son 2 stunda kosul karsilaniyor.

In [33]:
np.any(a>17, axis=0)

array([False, False, False,  True,  True])