In [3]:
import numpy as np

## Array Attribute'lari

### Shape

In [2]:
x = np.zeros((2,3))

print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
y = np.zeros((2,5,4))

print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [6]:
x.shape

(2, 3)

In [7]:
y.shape

(2, 5, 4)

### ndim
* Arrayin kac boyutlu olduguna bakabiliyoruz.

In [10]:
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
x.ndim

2

In [11]:
print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [9]:
y.ndim

3

### Size

In [14]:
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [16]:
x.size

6

In [17]:
y.size

40

### Dtype

In [18]:
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
x.dtype

dtype('float64')

## Reshapeing
* Onemli nokta reshape yapacagimiz yapinin sonraki yapiyla ayni eleman sayisina sahip olmasi, yani size'lari ayni olacak.

In [4]:
a = np.arange(1, 11)

In [5]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
a.ndim

1

In [7]:
a.size

10

In [8]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

* Eleman sayisi tutmaz ise hata verir

In [12]:
a.reshape(6,2)

ValueError: cannot reshape array of size 10 into shape (6,2)

## -1 ile Bout Karar Vermek

In [13]:
a.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

## Yeni Bir Boyut Eklemek

In [14]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
a[np.newaxis, :]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [17]:
a[: ,np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

* Bunun yerine None yazabiliriz.

In [18]:
a[None, :]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [19]:
a[:, None]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

## Concatenation
* Array Birlestirmek.

In [20]:
i = np.array([1,2,3,4])

In [22]:
u = np.array([5,6,7,8])

In [23]:
i

array([1, 2, 3, 4])

In [24]:
u

array([5, 6, 7, 8])

In [26]:
np.concatenate([i,u])

array([1, 2, 3, 4, 5, 6, 7, 8])

* Bunun yaninda bir python list ile numpy array birlestirebilirsiniz.

In [27]:
list = (10,11)

In [28]:
np.concatenate([i,u,list])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

* Sayilardan birisi float oldugu icin hepsini float yapti.

In [29]:
list2 = [10, 11, 11.2]

In [31]:
np.concatenate([i,u,list2])

array([ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. , 10. , 11. , 11.2])

In [32]:
list3 = [10, 11, "11.2"]

In [33]:
np.concatenate([i,u,list3])

array(['1', '2', '3', '4', '5', '6', '7', '8', '10', '11', '11.2'],
      dtype='<U21')

* Python tupple'larini da numpy arrayleri ile birlestirebiliriz.

In [34]:
list4 = (10,11)

In [35]:
np.concatenate([i,u,list4])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

## Size Mismatch

In [37]:
i

array([1, 2, 3, 4])

In [38]:
o = np.array([[1,2,3],
              [4,5,6]])

In [39]:
o

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
o.size

6

In [41]:
o.shape

(2, 3)

In [42]:
i.shape

(4,)

In [46]:
# shape mismatch
np.concatenate([i,o])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [47]:
np.concatenate([o,o])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [48]:
np.concatenate([o,o], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])