In [2]:
import numpy as np

## Stack
* Stack mantigi yeni dimension ekleyip o dimension uzerinden concatenation yaparak da saglayabiliriz.

In [2]:
a = np.array([1,2,3,4])

In [3]:
b = np.array([5,6,7,8])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
b

array([5, 6, 7, 8])

In [6]:
a.shape

(4,)

In [7]:
b.shape

(4,)

In [10]:
np.stack([a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
np.stack([a,b]).shape

(2, 4)

In [9]:
np.stack([a,b], axis=1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

## Split

* Index Bazli Boluyor

In [4]:
l = [10,20,30,40,50,60,70,80]

In [5]:
l

[10, 20, 30, 40, 50, 60, 70, 80]

In [6]:
# [0,1], [2,3,4,5], [6,7]
np.split(l,[2,6])

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80])]

In [7]:
np.split(l,[2,4,6])

[array([10, 20]), array([30, 40]), array([50, 60]), array([70, 80])]

In [8]:
a = np.array([10,20,30,40,50,60,70,80])

In [9]:
np.split(a,[2,5])

[array([10, 20]), array([30, 40, 50]), array([60, 70, 80])]

* split sonucunu birden cok elemana esitleyebiliriz.

In [11]:
p,o,i,u = np.split(l,[2,4,6])

In [12]:
p

array([10, 20])

In [13]:
o

array([30, 40])

In [14]:
i

array([50, 60])

In [15]:
u

array([70, 80])

### vsplit
* Vertical yani yatay split. Yatay bir sekilde boluyor.

In [16]:
a = np.arange(20).reshape(2,10)

In [17]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [18]:
np.vsplit(a,[1])[0]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [19]:
np.vsplit(a,[1])

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

### hsplit
* Horizontal yani dikey split. Dikay acidan boluyor.

In [21]:
a = np.arange(20).reshape(2,10)

In [22]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [23]:
np.hsplit(a,[2])

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3,  4,  5,  6,  7,  8,  9],
        [12, 13, 14, 15, 16, 17, 18, 19]])]

In [24]:
np.hsplit(a,[2])[1]

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [12, 13, 14, 15, 16, 17, 18, 19]])

In [29]:
np.hsplit(a,[2])[0]

array([[ 0,  1],
       [10, 11]])

In [30]:
np.hsplit(a,[2,6])

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3,  4,  5],
        [12, 13, 14, 15]]),
 array([[ 6,  7,  8,  9],
        [16, 17, 18, 19]])]

## Sorting

In [31]:
a = np.array([20,32,5,30,10])

In [32]:
a

array([20, 32,  5, 30, 10])

* np.sort(a) yazdigimizda deger guncellenmiyor.

In [33]:
np.sort(a)

array([ 5, 10, 20, 30, 32])

In [34]:
a

array([20, 32,  5, 30, 10])

* a.sort() yazidigimizda deger guncelleniyor.

In [35]:
a.sort()

In [39]:
a

array([ 5, 10, 20, 30, 32])

### argsort
* Kucukten buyuge siralanmis elemanlarin indexlerini dondurur

In [40]:
a = np.array([3,1,6,5,4,2])

In [41]:
idxs = np.argsort(a)

In [42]:
idxs

array([1, 5, 0, 4, 3, 2])